const Transactions = [
  {
    id: 1,
    type: "expense",
    date: "2024-06-01",
    userId: 1,
    accountId: 1,
    categoryId: 1,
    amount: 110,
    note: "note1",
    descrition: "description",
  },
  {
    id: 2,
    type: "expense",
    date: "2024-06-02",
    userId: 2,
    accountId: 2,
    categoryId: 2,
    amount: 120,
    note: "note2",
    descrition: "description",
  },
  {
    id: 3,
    type: "expense",
    date: "2024-06-03",
    userId: 3,
    accountId: 3,
    categoryId: 3,
    amount: 130,
    note: "note3",
    descrition: "description3",
  },
];
module.exports = Transactions;
